kind: pipeline
type: docker
name: testing

trigger:
  event:
    - pull_request
  branch:
    - staging
    - qa

steps:
  - name: build-and-test
    image: mcr.microsoft.com/playwright:v1.41.0-jammy 
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      GITHUB_TOKEN:
        from_secret: github_token 
    commands:
      # - docker build -t DevDeLeonJS/app-vite:latest .
      
      # - docker run -d --name app-container -p 3000:80 DevDeLeonJS/app-vite:latest
      
      # - sleep 10 
      
      - git clone https://$GITHUB_TOKEN@github.com/DevDeLeonJS/test-.git
      - cd test-
      - npm install
      - npx playwright install --with-deps 
      - npx playwright test
      
      # - docker stop app-container
      # - docker rm app-container

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock